### PR TITLE
update russian translation of the book

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by AfoHT** [comment]
Nice that there is interest to bring the translation of the book up to date, unfortunately I do not speak Russian so I cannot judge the content.

The current book as found on the master branch is for v0.6 but incomplete, newer changes such as monotonic etc has not been properly documented (since early stages, still alpha.1).

If I understand correctly the updated translation mirrors the current docs as available in latest master?

Then later on we'll need to do an update to the translation as well when final release of 0.6 comes around.

The tests fails due to monotonic, unrelated to the documentation changes

**Comment by burrbull** [comment]
> If I understand correctly the updated translation mirrors the current docs as available in latest master?

Yes, you are right. I'll disable those pages temporary as it's done in master.

**Comment by korken89** [comment]
If this is rebased on master the tests will pass again.

**Comment by burrbull** [comment]
Done

**Review by korken89 — APPROVED** [review]
bors merge

**Pull request merged**
