### PR TITLE
GHA: Tune CI

### PR DESCRIPTION
**Pull request by AfoHT**
- GHA: Use rust-cache
- GHA: Cleanup single target jobs
- GHA: Add cargo clippy

### CODE REVIEW

**Review by korken89 — DISMISSED** [review]
bors merge

**Comment by AfoHT** [comment]
bors retry

**Comment by AfoHT** [comment]
bors retry

**Review by perlindgren — APPROVED** [review]
bors merga

**Comment by AfoHT** [comment]
bors merge

**Pull request merged**
