### PR TITLE
Bump cortex-m to 0.7.0

### PR DESCRIPTION
**Pull request by nickray**

### CODE REVIEW

**Comment by nickray** [comment]
Uff, what a mess. It would be unfortunate if the new 0.6 release would be stuck on the old `cortex-m`.

**Comment by nickray** [comment]
Alright, pending merge of https://github.com/japaric/lm3s6965/pull/4 it seems there's no issue bumping cortex-m.

**Comment by nickray** [comment]
PR was merged.

**Comment by korken89** [comment]
Hi, some tests are failing. Can you have a look at why this is?

**Comment by nickray** [comment]
I think this is the update to Rust 1.49. The testv7/testv6 tests seem brittle in this respect; I don't think there's a way in trybuild to skip specific output lines?

**Review by korken89 — APPROVED** [review]
Thanks for updating!

**Comment by nickray** [comment]
What went wrong here @korken89 ?

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
Hmm, not sure what is going wrong here. I'll have to take a deeper look.

**Comment by korken89** [comment]
bors retry

**Comment by AfoHT** [comment]
bors retry

**Comment by AfoHT** [comment]
bors retry

**Pull request merged**
