### PR TITLE
validate unused dispatchers

### LINKED ISSUE #521: Unused `dispatchers` are not checked for validity
The `task` example requires two dispatchers.

When a required dispatcher is invalid, e.g. 
```rust
#[rtic::app(device = lm3s6965, dispatchers = [SSI0, FOO])]
```
behavior is expected:
```
error[E0599]: no variant or associated item named `FOO` found for enum `Interrupt` in the current scope
  --> examples\task.rs:10:53
   |
10 | #[rtic::app(device = lm3s6965, dispatchers = [SSI0, FOO])]
   |                                                     ^^^ variant or associated item not found in `Interrupt`
```

However, when the dispatcher is not needed (yet):
```rust
#[rtic::app(device = lm3s6965, dispatchers = [SSI0, QEI0, FOO])]
```

The build succeeds, unexpectedly. When another priority is used, this will cause an unexpected error.

### PR DESCRIPTION
**Pull request by japaric**
closes #521

### CODE REVIEW

**Review by perlindgren — DISMISSED** [review]
Nice, even simpler than before!

**Review by perlindgren — APPROVED** [review]
Even better, tests pass ;)

**Review by perlindgren — APPROVED** [review]
Let's hope for the line break fix to fix the problem.

**Review by AfoHT — APPROVED** [review]
bors merge

**Pull request merged**
