### PR TITLE
Now all locks are symmetric

### PR DESCRIPTION
**Pull request by korken89**

### CODE REVIEW

**Review by AfoHT — APPROVED** [review]
bors merge

**Comment by little-arhat** [comment]
Hello!

I see that Changelog lists this as breaking change:
```
    [breaking-change] PR 399 Locking resources are now always required to achieve a symmetric UI.
```

where do I find more information about what has been broken? 

` No description provided. ` is not clear enough for me %(

**Comment by mattico** [comment]
@little-arhat check out https://rtic.rs/dev/book/en/migration/migration_v5.html#symmetric-locks

**Comment by little-arhat** [comment]
@mattico thank you! I was trying https://rtic.rc/0.6 and the likes, but didn't think about dev.

Maybe it's worth adding this link to readme? (Somewhere in the bottom part of it, I suppose).

**Pull request merged**
